### PR TITLE
Format addressDataType if no firstname or lastname set

### PR DESCRIPTION
**Pull request by mattgrul**
Format CustomerAddressDataType.php to remove space and comma if no firstname or lastname are set.

Before
Screenshot from 2021-07-01 16-33-26

After
Screenshot from 2021-07-01 16-32-45

### CODE REVIEW

**Comment by Vinai** [comment]
Thanks! Once the actions are through I'll happily merge!

**Comment by mattgrul** [comment]
Thanks Vinai!

**Comment by Vinai** [comment]
I've checked locally that the broken integration tests are resolved after rebasing on main, so I'll go ahead and merge.

Thanks again for contributing

**Comment by mattgrul** [comment]
Amazing, no problem!

**Pull request merged**
